### ISSUE TITLE
Crash while trying to load a SUMO XML file using the "ParseXML" option 

### ISSUE THREAD

**Issue by akrishnamachar1** [AugmentedDesignLab/Sumo2Unreal#4]
Hi, I was able to compile and open the editor on my Ubuntu 16.04 computer, however when I try to use the "ParseXML" option in the editor to select and load any SUMO XML file, the editor immediately crashes. I have tried this for both the provided SUMO XML files as well as ones that I generated on my own.

I've included the crash log for reference - it looks like something is triggering an Array index out of bounds error, but I'm not sure where in the code it's being caused.

[SumoToUnreal.log](https://github.com/AugmentedDesignLab/Sumo2Unreal/files/2830075/SumoToUnreal.log)

As an aside, I had to make one small change to the code in order to get it to compile on my computer. I was getting a TCHAR* error from Sources/Plugins/ParseXML/Source/ParseXML/fileParser.cpp, so I fixed it by adjusting the UfileParser::loadxml() function as follows (I would have opened new branch/pull request to fix this, but I don't have write permission on this repository): 

```
bool UfileParser::loadxml()
{
	UE_LOG(LogEngine, Warning, TEXT("Loading started"));
	FText outError;
	int32 outErrorNum;
        FString Text = "";
        bool success = FFastXml::ParseXmlFile((IFastXmlCallback*)(this), selectedXMLFile.GetCharArray().GetData(),
                                          (TCHAR*)*Text, nullptr, false, false, outError, outErrorNum);
	return success;
}
```

**Comment by ishaan95** [comment]
Hi, 
Please pull the latest version of the repository. It should work now. 

In the ParseXML.cpp file, PluginButtonClicked() function, a TArray was not being copied on ubuntu which led to incorrect indexing.
